USE `gamovie`;
INSERT INTO `roles` VALUES (1,'ROLE_ADMIN'),(3,'ROLE_PREMIUM'),(2,'ROLE_USER');

INSERT INTO `gamovie`.`users` (`email`, `name`, `password`) VALUES ('admin@gmail.com', 'Admin', '$2a$10$4FYqaCBAtGuukqhX0tMlc.uhBI.AQLBTt.abFEXASr5U4KNsEqHr2');
INSERT INTO `gamovie`.`users` (`email`, `name`, `password`) VALUES ('ivan@gmail.com', 'Ivan', '$2a$10$4FYqaCBAtGuukqhX0tMlc.uhBI.AQLBTt.abFEXASr5U4KNsEqHr2');
INSERT INTO `gamovie`.`users` (`email`, `name`, `password`) VALUES ('raul@gmail.com', 'Raul', '$2a$10$4FYqaCBAtGuukqhX0tMlc.uhBI.AQLBTt.abFEXASr5U4KNsEqHr2');
INSERT INTO `gamovie`.`users` (`email`, `name`, `password`) VALUES ('jose@gmail.com', 'Jose', '$2a$10$4FYqaCBAtGuukqhX0tMlc.uhBI.AQLBTt.abFEXASr5U4KNsEqHr2');
INSERT INTO `gamovie`.`users` (`email`, `name`, `password`) VALUES ('carmen@gmail.com', 'Carmen', '$2a$10$4FYqaCBAtGuukqhX0tMlc.uhBI.AQLBTt.abFEXASr5U4KNsEqHr2');

INSERT INTO `gamovie`.`users_roles`
(`role_id`,
`user_id`)
VALUES
(1,1);
INSERT INTO `gamovie`.`users_roles`
(`role_id`,
`user_id`)
VALUES
(2,2);
INSERT INTO `gamovie`.`users_roles`
(`role_id`,
`user_id`)
VALUES
(2,3);
INSERT INTO `gamovie`.`users_roles`
(`role_id`,
`user_id`)
VALUES
(2,4);
INSERT INTO `gamovie`.`users_roles`
(`role_id`,
`user_id`)
VALUES
(2,5);

#MOVIES

INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Thriller', '2022-04-26', 'Matt Reeves', 'Warner Bros', 'theBatman.jpg', '10', 'The Batman', '7.1', 'Después de dos años acechando por las calles de la ciudad como Batman (Robert Pattinson), e infundiendo miedo en las mentes perversas de los criminales, Bruce Wayne está sumido en las profundidades de las sombras de Gotham City. Este vigilante solitario cuenta con pocos aliados de confianza y eso le ha llevado a convertirse en la única encarnación de la venganza entre sus conciudadanos. Cuando un asesino apunta a la élite de Gotham con una serie de maquinaciones sádicas, un rastro de pistas crípticas lleva a Batman a realizar una investigación en el inframundo. ', '2022');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Superhéroes', '2022-04-26', 'Jon Watts', 'Marvel', 'https://image.tmdb.org/t/p/w500/osYbtvqjMUhEXgkuFJOsRYVpq6N.jpg', '10', 'Spider-Man: No Way Home', '7.2', 'Por primera vez en la historia cinematográfica de Spider-Man, nuestro héroe, vecino y amigo es desenmascarado, y por tanto, ya no es capaz de separar su vida normal de los enormes riesgos que conlleva ser un superhéroe. Cuando pide ayuda al Doctor Strange, los riesgos pasan a ser aún más peligrosos, obligándole a descubrir lo que realmente significa ser él. Secuela de Spider-Man: Far From Home.', '2021');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Ciencia ficción', '2022-04-26', 'Denis Villeneuve', 'Legendary Pictures', 'dune.jpg', '10', 'Dune', '7.3', 'En el Año 10191 el desértico planeta Arrakis, feudo de la familia Harkonnen desde hace generaciones, queda en manos de la Casa de los Atreides por orden del emperador. Con ello les cede la explotación de las reservas de especia, la materia prima más valiosa de la galaxia, necesaria para los viajes interestelares y también una droga capaz de amplificar la conciencia y extender la vida. El duque Leto (Oscar Isaac), la dama Jessica (Rebecca Ferguson) y el hijo de ambos, Paul Atreides (Timothée Chalamet), llegan a Arrakis con la esperanza de mantener el buen nombre de su casa y ser fieles al emperador, pero pronto se verán envueltos en una trama de traiciones y engaños que les llevará a cuestionar su confianza entre sus más allegados y a valorar a los lugareños, los Fremen, una estirpe de habitantes del desierto con una estrecha relación con la especia.', '2021');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Acción', '2022-04-26', 'Adam Wingard', 'Warner Bros', 'godzillaKong.jpg', '10', 'Godzilla vs. Kong', '5.3', 'Godzilla y Kong, dos de las fuerzas más poderosas de un planeta habitado por todo tipo de aterradoras criaturas, se enfrentan en un espectacular combate que sacude los cimientos de la humanidad. Kong y sus protectores emprenderán un peligroso viaje para encontrar su verdadero hogar. Con ellos está Jia, una joven huérfana con la que el gigante tiene un vínculo único y poderoso. En el camino se cruzan inesperadamente con el de un Godzilla enfurecido que va causando destrucción a su paso por el mundo. El choque épico entre los dos titanes -provocado por fuerzas invisibles- es solo el comienzo del misterio que se esconde en las profundidades del núcleo de la Tierra.', '2021');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Ciencia ficción', '2022-04-26', 'Barry Sonnenfeld', 'Columbia Pictures', 'menInBlack.jpg', '10', 'Men in Black', '6.2', 'Durante muchos años los extraterrestres han vivido en la Tierra, mezclados con los seres humanos, sin que nadie lo supiese. Los Hombres de Negro son agentes especiales que forman parte de una unidad altamente secreta del gobierno; su misión consiste en controlar a los alienígenas. Dos de estos agentes (uno veterano y otro recién incorporado), cuya misión consiste en vigilar a los alienígenas que viven en Nueva York, descubren a un terrorista galáctico que pretende acabar con la Humanidad', '2006');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Thriller', '2022-04-26', 'Christopher Nolan', 'Warner Bros', 'batmanBegins.jpg', '10', 'Batman Begins', '7.4', 'Nueva adaptación del famoso cómic. Narra los orígenes de la leyenda de Batman y los motivos que lo convirtieron en el representante del Bien en la ciudad de Gotham. Bruce Wayne vive obsesionado con el recuerdo de sus padres, muertos a tiros en su presencia. Atormentado por el dolor, se va de Gotham y recorre el mundo hasta que encuentra a un extraño personaje que lo adiestra en todas las disciplinas físicas y mentales que le servirán para combatir el Mal. Por esta razón, la Liga de las Sombras, una poderosa y subversiva sociedad secreta, dirigida por el enigmático Ra`s Al Ghul, intenta reclutarlo. Cuando Bruce vuelve a Gotham, la ciudad está dominada por el crimen y la corrupción. Con la ayuda de su leal mayordomo Alfred, del detective de la policía Jim Gordon y de Lucius Fox, su colega en una Sociedad de Ciencias Aplicadas, Wayne libera a su alter ego: Batman, un justiciero enmascarado que utiliza la fuerza, la inteligencia y la más alta tecnología para luchar contra las siniestras fuerzas que amenazan con destruir la ciudad.', '2007');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Thriller', '2022-04-26', 'Christopher Nolan', 'Warner Bros', 'caballerOscuro.jpg', '10', 'El Caballero Oscuro', '8.1', 'Batman/Bruce Wayne (Christian Bale) regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon (Gary Oldman) y del Fiscal del Distrito Harvey Dent (Aaron Eckhart), Batman se propone destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra su eficacia, pero, de repente, aparece Joker (Heath Ledger), un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.', '2008');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Thriller', '2022-04-26', 'Christopher Nolan', 'Warner Bros', 'caballerOscuroRenace.jpg', '10', 'El caballero oscuro: La leyenda renace', '7.5', 'Hace ocho años que Batman desapareció, dejando de ser un héroe para convertirse en un fugitivo. Al asumir la culpa por la muerte del fiscal del distrito Harvey Dent, el Caballero Oscuro decidió sacrificarlo todo por lo que consideraba, al igual que el Comisario Gordon, un bien mayor. La mentira funciona durante un tiempo, ya que la actividad criminal de la ciudad de Gotham se ve aplacada gracias a la dura Ley Dent. Pero todo cambia con la llegada de una astuta gata ladrona que pretende llevar a cabo un misterioso plan. Sin embargo, mucho más peligrosa es la aparición en escena de Bane, un terrorista enmascarado cuyos despiadados planes obligan a Bruce a regresar de su voluntario exilio.', '2012');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Peter Jackson', 'New Line Cinema', 'comunidadAnillo.jpg', '10', 'El señor de los anillos: La comunidad del anillo', '8.0', 'En la Tierra Media, el Señor Oscuro Sauron ordenó a los Elfos que forjaran los Grandes Anillos de Poder. Tres para los reyes Elfos, siete para los Señores Enanos, y nueve para los Hombres Mortales. Pero Saurón también forjó, en secreto, el Anillo Único, que tiene el poder de esclavizar toda la Tierra Media. Con la ayuda de sus amigos y de valientes aliados, el joven hobbit Frodo emprende un peligroso viaje con la misión de destruir el Anillo Único. Pero el malvado Sauron ordena la persecución del grupo, compuesto por Frodo y sus leales amigos hobbits, un mago, un hombre, un elfo y un enano. La misión es casi suicida pero necesaria, pues si Sauron con su ejército de orcos lograra recuperar el Anillo, sería el final de la Tierra Media.', '2001');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Peter Jackson', 'New Line Cinema', 'dosTorres.jpg', '10', 'El señor de los anillos: Las dos torres', '8.0', 'Tras la disolución de la Compañía del Anillo, Frodo y su fiel amigo Sam se dirigen hacia Mordor para destruir el Anillo Único y acabar con el poder de Sauron, pero les sigue un siniestro personaje llamado Gollum. Mientras, y tras la dura batalla contra los orcos donde cayó Boromir, el hombre Aragorn, el elfo Legolas y el enano Gimli intentan rescatar a los medianos Merry y Pipin, secuestrados por los orcos de Mordor. Por su parte, Saurón y el traidor Sarumán continúan con sus planes en Mordor, a la espera de la guerra contra las razas libres de la Tierra Media', '2002');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Peter Jackson', 'New Line Cinema', 'retornoRey.jpg', '10', 'El señor de los anillos: El retorno del rey', '8.2', 'Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de decidir el destino de la Tierra Media, y, por primera vez, parece que hay una pequeña esperanza. El interés del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, cuyo trono será reclamado por Aragorn. Sauron se dispone a lanzar un ataque decisivo contra Gondor. Mientras tanto, Frodo y Sam continuan su camino hacia Mordor, con la esperanza de llegar al Monte del Destino.', '2003');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Peter Jackson', 'New Line Cinema', 'hobbitViajeInesperado.jpg', '10', 'El Hobbit: Un viaje inesperado', '7', 'Precuela de la trilogía "El Señor de los Anillos", obra de J.R.R. Tolkien. En compañía del mago Gandalf y de trece enanos, el hobbit Bilbo Bolsón emprende un viaje a través del país de los elfos y los bosques de los trolls, desde las mazmorras de los orcos hasta la Montaña Solitaria, donde el dragón Smaug esconde el tesoro de los Enanos. Finalmente, en las profundidades de la Tierra, encuentra el Anillo Único, hipnótico objeto que será posteriormente causa de tantas sangrientas batallas en la Tierra Media.', '2012');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Peter Jackson', 'New Line Cinema', 'hobbitSmaug.jpg', '10', 'El Hobbit: La desolación de Smaug', '6.7', '"El Hobbit: La Desolación de Smaug" continua la aventura de Bilbo Bolsón en su viaje con el mago Gandalf y trece enanos liderados por Thorin Escudo de Roble en una búsqueda épica para reclamar el reino enano de Erebor. En su camino toparán con multitud de peligros y harán frente al temible dragón Smaug.', '2013');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Peter Jackson', 'New Line Cinema', 'hobbit5Ejercitos.jpg', '10', 'El Hobbit: La batalla de los cinco ejércitos', '6.3', 'Después de haber recuperado el reino del Dragón Smaug en la montaña, la Compañía ha desencadenado, sin querer, una potencia maligna. Un Smaug enfurecido vuela hacia la Ciudad del Lago para acabar con cualquier resto de vida. Obsesionado con las enormes riquezas en su poder, el rey enano Thorin se vuelve codicioso, mientras Bilbo intenta hacerle entrar en razón haciendo algo desesperado y peligroso. Pero hay aún mayores peligros por delante. Sin la ayuda del mago Gandalf, su gran enemigo Sauron ha enviado legiones de orcos hacia la Montaña Solitaria en un ataque épico. Cuando la oscuridad se cierna sobre ellos, las razas de los Enanos, Elfos y Hombres deberán decidir si unirse o ser destruidos. Bilbo se encontrará así en la batalla épica de los Cinco Ejércitos, donde el futuro de la Tierra Media está en juego.', '2014');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Ciencia ficción', '2022-04-26', 'George Lucas', 'Lucasfilm', 'amenazaFantasma.jpg', '10', 'La guerra de las galaxias. Episodio I: La amenaza fantasma', '6.2', 'Ambientada treinta años antes que "La guerra de las galaxias" (1977), muestra la infancia de Darth Vader, el pasado de Obi-Wan Kenobi y el resurgimiento de los Sith, los caballeros Jedi dominados por el Lado Oscuro. La Federación de Comercio ha bloqueado el pequeño planeta de Naboo, gobernado por la joven Reina Amidala; se trata de un plan ideado por Sith Darth Sidious, que, manteniéndose en el anonimato, dirige a los neimoidianos, que están al mando de la Federación. El Jedi Qui-Gon Jinn y su aprendiz Obi-Wan Kenobi convencen a Amidala para que vaya a Coruscant, la capital de la República y sede del Consejo Jedi, y trate de neutralizar esta amenaza. Pero, al intentar esquivar el bloqueo, la nave real resulta averiada, viéndose así obligada la tripulación a aterrizar en el desértico y remoto planeta de Tatooine.', '1999');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Ciencia ficción', '2022-04-26', 'George Lucas', 'Lucasfilm', 'ataqueClones.jpg', '10', 'La guerra de las galaxias. Episodio II: El ataque de los clones', '6.3', 'Corren tenebrosos tiempos para la República, que continúa envuelta en luchas y sumida en el caos. Un movimiento separatista, formado por centenares de planetas y poderosas alianzas encabezadas por el misterioso conde Dooku, amenaza la galaxia. Ni siquiera los Jedi parecen capaces de conjurar el peligro. Este movimiento provoca el estallido de las guerras clones, que representa el principio del fin de la República. Para allanar el camino, los separatistas intentan asesinar a la senadora Padme Amidala. Para evitar futuros atentados, su seguridad es encomendada a dos caballeros Jedi.', '2002');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Ciencia ficción', '2022-04-26', 'George Lucas', 'Lucasfilm', 'venganzaSith.jpg', '10', 'La guerra de las galaxias. Episodio III: La venganza de los Sith', '7.1', 'Último capítulo de la trilogía de precuelas de Star Wars, en el que Anakin Skywalker definitivamente se pasa al lado oscuro. En el Episodio III aparece el General Grievous, un ser implacable mitad-alien mitad-robot, el líder del ejército separatista Droid. Los Sith son los amos del lado oscuro de la Fuerza y los enemigos de los Jedi. Fueron prácticamente exterminados por los Jedi hace mil años, pero esta orden del mal sobrevivió en la clandestinidad.', '2005');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Ciencia ficción', '2022-04-26', 'George Lucas', 'Lucasfilm', 'nuevaEsperanza.jpg', '10', 'La guerra de las galaxias. Episodio IV: Una nueva esperanza', '7.9', 'La princesa Leia, líder del movimiento rebelde que desea reinstaurar la República en la galaxia en los tiempos ominosos del Imperio, es capturada por las Fuerzas Imperiales, capitaneadas por el implacable Darth Vader, el sirviente más fiel del Emperador. El intrépido y joven Luke Skywalker, ayudado por Han Solo, capitán de la nave espacial "El Halcón Milenario", y los androides, R2D2 y C3PO, serán los encargados de luchar contra el enemigo e intentar rescatar a la princesa para volver a instaurar la justicia en el seno de la galaxia.', '1977');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Ciencia ficción', '2022-04-26', 'George Lucas', 'Lucasfilm', 'imperioContraataca.jpg', '10', 'La guerra de las galaxias. Episodio V: El imperio contraataca', '8.1', 'Tras un ataque sorpresa de las tropas imperiales a las bases camufladas de la alianza rebelde, Luke Skywalker, en compañía de R2D2, parte hacia el planeta Dagobah en busca de Yoda, el último maestro Jedi, para que le enseñe los secretos de la Fuerza. Mientras, Han Solo, la princesa Leia, Chewbacca, y C3PO esquivan a las fuerzas imperiales y piden refugio al antiguo propietario del Halcón Milenario, Lando Calrissian, en la ciudad minera de Bespin, donde les prepara una trampa urdida por Darth Vader.', '1980');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Ciencia ficción', '2022-04-26', 'Richard Marquand', 'Lucasfilm', 'retornoJedi.jpg', '10', 'La guerra de las galaxias. Episodio VI: El retorno del Jedi', '7.9', 'Para ir a Tatooine y liberar a Han Solo, Luke Skywalker y la princesa Leia deben infiltrarse en la peligrosa guarida de Jabba the Hutt, el gángster más temido de la galaxia. Una vez reunidos, el equipo recluta a tribus de Ewoks para combatir a las fuerzas imperiales en los bosques de la luna de Endor. Mientras tanto, el Emperador y Darth Vader conspiran para atraer a Luke al lado oscuro, pero el joven está decidido a reavivar el espíritu del Jedi en su padre. La guerra civil galáctica termina con un último enfrentamiento entre las fuerzas rebeldes unificadas y una segunda Estrella de la Muerte, indefensa e incompleta, en una batalla que decidirá el destino de la galaxia.', '1983');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Acción', '2022-04-26', 'Ruben Fleischer', 'Sony Pictures Entertainment', 'uncharted.jpg', '10', 'Uncharted', '5.8', 'Basada en una de las series de videojuegos más vendidas y aclamadas por la crítica de todos los tiempos, "Uncharted" presenta a un joven, astuto y carismático, Nathan Drake (Tom Holland) en su primera aventura como cazatesoros con su ingenioso compañero Victor “Sully” Sullivan (Mark Wahlberg). En una aventura de acción que se extiende por todo el mundo, ambos se embarcan en una peligrosa búsqueda de “el mayor tesoro nunca antes encontrado” al tiempo que rastrean las claves que les podrían conducir al hermano de Nathan, perdido hace ya mucho tiempo.', '2022');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Drama', '2022-04-26', 'Tony Kaye', 'New Line Cinema', 'american.jpg', '10', 'American History X', '8.3', 'Derek (Edward Norton), un joven "skin head" californiano de ideología neonazi, es encarcelado por asesinar a un negro que pretendía robarle su furgoneta. Cuando sale de prisión y regresa a su barrio dispuesto a alejarse del mundo de la violencia, se encuentra con que su hermano pequeño (Edward Furlong), para quien Derek es el modelo a seguir, sigue el mismo camino que a él lo condujo a la cárcel.', '1998');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Bélica', '2022-04-26', 'Quentin Tarantino', 'Universal Pictures', 'bastards.jpg', '10', 'Malditos bastardos', '7.8', 'Segunda Guerra Mundial (1939-1945). En la Francia ocupada por los alemanes, Shosanna Dreyfus (Mélanie Laurent) presencia la ejecución de su familia por orden del coronel Hans Landa (Christoph Waltz). Después de huir a París, adopta una nueva identidad como propietaria de un cine. En otro lugar de Europa, el teniente Aldo Raine (Brad Pitt) adiestra a un grupo de soldados judíos ("The Basterds") para atacar objetivos concretos. Los hombres de Raine y una actriz alemana (Diane Kruger), que trabaja para los aliados, deben llevar a cabo una misión para hacer caer a los jefes del Tercer Reich. El destino quiere que todos se encuentren bajo la marquesina de un cine donde Shosanna espera para vengarse.', '2009');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Bélica', '2022-04-26', 'Jean-Jacques Annaud', 'Paramount Pictures', 'enemigoPuertas.jpg', '10', 'Enemigo a las puertas', '7.6', 'Año 1942, en plena Segunda Guerra Mundial. Mientras los ejércitos de Alemania y Rusia luchan encarnizadamente y el mundo espera con ansiedad el desenlace de la batalla de Stalingrado, un francotirador ruso, Vassili Zaitsev, persevera en la empresa de eliminar a sus enemigos uno por uno. Danilov -el oficial encargado de la propaganda soviética- lo convierte en un héroe nacional que debe servir de ejemplo para animar a las tropas a proseguir la lucha contra el ejército alemán. Los alemanes, por su parte, envían a su mejor francotirador, el mayor König, para que elimine a Vassili.', '2001');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Bélica', '2022-04-26', 'Sam Mendes', 'Universal Pictures', '1917.jpg', '10', '1917', '7.7', 'En lo más crudo de la Primera Guerra Mundial, dos jóvenes soldados británicos, Schofield (George MacKay) y Blake (Dean-Charles Chapman) reciben una misión aparentemente imposible. En una carrera contrarreloj, deberán atravesar el territorio enemigo para entregar un mensaje que evitará un mortífero ataque contra cientos de soldados, entre ellos el propio hermano de Blake.', '2019');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Bélica', '2022-04-26', 'Steven Spielberg', 'DreamWorks', 'salvarRyan.jpg', '10', 'Salvar al soldado Ryan', '7.8', 'Segunda Guerra Mundial, 1944. Tras el desembarco de los Aliados en Normandía, a un grupo de soldados americanos se le encomienda una peligrosa misión: poner a salvo al soldado James Ryan. Los hombres de la patrulla del capitán John Miller deben arriesgar sus vidas para encontrar a este soldado, cuyos tres hermanos han muerto en la guerra. Lo único que se sabe del soldado Ryan es que se lanzó con su escuadrón de paracaidistas detrás de las líneas enemigas.', '1998');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Bélica', '2022-04-26', 'Roman Polanski', 'R.P. Productions', 'pianista.jpg', '10', 'El pianista', '8.2', 'Wladyslaw Szpilman, un brillante pianista polaco de origen judío, vive con su familia en el ghetto de Varsovia. Cuando, en 1939, los alemanes invaden Polonia, consigue evitar la deportación gracias a la ayuda de algunos amigos. Pero tendrá que vivir escondido y completamente aislado durante mucho tiempo, y para sobrevivir tendrá que afrontar constantes peligros.', '2002');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Bélica', '2022-04-26', 'Steven Spielberg', 'DreamWorks', 'warHorse.jpg', '10', 'War Horse', '6.5', 'En un pueblo inglés, Albert, el hijo de un granjero, ve nacer un potrillo. Poco después, su padre lo adquiere en una subasta, y el chico le pone de nombre Joey. Pero la familia se arruina y no tiene más remedio que vender el caballo justo cuando estalla la Primera Guerra Mundial (1914-1918). Ése es el punto de partida de un viaje en el que tanto Albert como Joey lucharán por sobrevivir a la contienda y volver a estar juntos.', '2011');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Accion', '2022-04-26', 'Gore Verbinski', 'Walt Disney Pictures', 'piratasDelCaribe.jpg', '10', 'Piratas del Caribe: La maldición de la Perla Negra', '7.2', 'Mar Caribe, siglo XVIII. El aventurero capitán Jack Sparrow piratea en aguas caribeñas, pero su andanzas terminan cuando su enemigo, el Capitán Barbossa, después de robarle su barco, el Perla Negra, ataca la ciudad de Port Royal y secuestra a Elizabeth Swann, la hija del Gobernador. Will Turner, amigo de la infancia de Elizabeth, se une a Jack para rescatarla y recuperar el Perla Negra. Pero Barbossa y su tripulación son víctimas de un conjuro que los condena a vivir eternamente y a transformarse cada noche en esqueletos vivientes. El conjuro sólo puede romperse si devuelven una pieza de oro azteca y saldan una deuda de sangre. El rescate de la bella Elizabeth será una tarea difícil, pues la maldición es real y será difícil enfrentarse con quienes no pueden morir.', '2003');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Superhéroes', '2022-04-26', 'Anthony Russo', 'Marvel', 'infinity.jpg', '10', 'Vengadores: Infinity War', '7.5', 'El todopoderoso Thanos ha despertado con la promesa de arrasar con todo a su paso, portando el Guantelete del Infinito, que le confiere un poder incalculable. Los únicos capaces de pararle los pies son los Vengadores y el resto de superhéroes de la galaxia, que deberán estar dispuestos a sacrificarlo todo por un bien mayor. Capitán América e Ironman deberán limar sus diferencias, Black Panther apoyará con sus tropas desde Wakanda, Thor y los Guardianes de la Galaxia e incluso Spider-Man se unirán antes de que los planes de devastación y ruina pongan fin al universo. ¿Serán capaces de frenar el avance del titán del caos?', '2018');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Superhéroes', '2022-04-26', 'Anthony Russo', 'Marvel', 'endGame.jpg', '10', 'Vengadores: Endgame', '7.3', 'Después de los eventos devastadores de "Avengers: Infinity War", el universo está en ruinas debido a las acciones de Thanos, el Titán Loco. Con la ayuda de los aliados que quedaron, los Vengadores deberán reunirse una vez más para intentar deshacer sus acciones y restaurar el orden en el universo de una vez por todas, sin importar cuáles son las consecuencias... Cuarta y última entrega de la saga "Vengadores".', '2019');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Thriller', '2022-04-26', 'F. Gary Gray', 'The Film Department', 'ciudadanoEjemplar.jpg', '10', 'Un ciudadano ejemplar', '7.0', 'Clyde Shelton (Gerard Butler) es un hombre que lo ha perdido todo: diez años atrás su mujer y su hija fueron brutalmente asesinadas, pero el verdadero criminal no fue condenado. El responsable de esta injusticia es Nick Rice (Jamie Foxx), el ambicioso ayudante del fiscal del distrito, que hizo un pacto con el abogado de uno de los asesinos. Pero Clyde no ha olvidado lo sucedido, y ha esperado todo este tiempo para poder llevar a cabo su venganza implacable.', '2009');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Acción', '2022-04-26', 'Ridley Scott', 'Universal Pictures', 'gladiator.jpg', '10', 'Gladiator', '7.9', 'En el año 180, el Imperio Romano domina todo el mundo conocido. Tras una gran victoria sobre los bárbaros del norte, el anciano emperador Marco Aurelio (Richard Harris) decide transferir el poder a Máximo (Russell Crowe), bravo general de sus ejércitos y hombre de inquebrantable lealtad al imperio. Pero su hijo Cómodo (Joaquin Phoenix), que aspiraba al trono, no lo acepta y trata de asesinar a Máximo.', '2000');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Western', '2022-04-26', 'Alejandro González Iñárritu', '20th Century Fox', 'revenant.jpg', '10', 'El Renacido', '7.2', 'Año 1823. En las profundidades de la América salvaje, el explorador Hugh Glass (Leonardo DiCaprio) participa junto a su hijo mestizo Hawk en una expedición de tramperos que recolecta pieles. Glass resulta gravemente herido por el ataque de un oso y es abandonado a su suerte por un traicionero miembro de su equipo, John Fitzgerald (Tom Hardy). Con la fuerza de voluntad como su única arma, Glass deberá enfrentarse a un territorio hostil, a un invierno brutal y a la guerra constante entre las tribus de nativos americanos, en una búsqueda implacable para conseguir vengarse.', '2015');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Western', '2022-04-26', 'Quentin Tarantino', 'Sony Pictures Entertainment', 'django.jpg', '10', 'Django desencadenado', '7.9', 'En Texas, dos años antes de estallar la Guerra Civil Americana, King Schultz (Christoph Waltz), un cazarrecompensas alemán que sigue la pista a unos asesinos para cobrar por sus cabezas, le promete al esclavo negro Django (Jamie Foxx) dejarlo en libertad si le ayuda a atraparlos. Él acepta, pues luego quiere ir a buscar a su esposa Broomhilda (Kerry Washington), esclava en una plantación del terrateniente Calvin Candie (Leonardo DiCaprio).', '2012');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Western', '2022-04-26', 'Antoine Fuqua', 'Sony Pictures Entertainment', '7magnificos.jpg', '10', 'Los 7 magníficos', '5.9', 'Los habitantes de Rose Creek, atemorizados bajo el control del industrial Bartholomew Bogue, deciden contratar a siete forajidos para terminar con la amenaza: Sam Chisolm (Denzel Washington), Josh Faraday (Chris Pratt), Goodnight Robicheaux (Ethan Hawke), Jack Home (Vincent D´Onofrio), Billy Rocks (Byung-Hun Lee), Vasquez (Manuel García Rulfo) y Red Harvest (Martin Sensmeier). Sin embargo, pronto se darán cuenta estos siete que están luchando por algo más que el simple dinero. Remake del western homónimo de John Sturges, a su vez remake de "Los siete samuráis" de Akira Kurosawa.', '2016');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Chris Columbus', 'Warner Bros', 'harry1.jpg', '10', 'Harry Potter y la piedra filosofal', '6.8', 'El día en que cumple once años, Harry Potter se entera de que es hijo de dos destacados hechiceros, de los que ha heredado poderes mágicos. En la escuela Hogwarts de Magia y Hechicería, donde se educa con otros niños que también tienen poderes especiales, aprenderá todo lo necesario para ser mago.', '2001');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Chris Columbus', 'Warner Bros', 'harry2.jpg', '10', 'Harry Potter y la cámara secreta', '6.5', 'Terminado el verano, Harry (Radcliffe) no ve la hora de abandonar la casa de sus odiosos tíos, pero, inesperadamente se presenta en su dormitorio Dobby, un elfo doméstico, que le anuncia que correrá un gran peligro si vuelve a Hogwarts. A pesar de los esfuerzos del elfo por retenerlo, Harry es rescatado por Ron y sus hermanos, con la ayuda de un coche volador, y recibido con los brazos abiertos en el cálido hogar de los Weasley.', '2002');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Alfonso Cuarón', 'Warner Bros', 'harry3.jpg', '10', 'Harry Potter y el prisionero de Azkaban', '6.9', 'Cuando Harry Potter y sus amigos vuelven a Hogwarts para cursar su tercer año de estudios, se ven involucrados en un misterio: de la prisión para magos de Azkaban se ha fugado Sirius Black, un peligroso mago que fue cómplice de Lord Voldemort y que intentará vengarse de Harry Potter. El joven aprendiz de mago contribuyó en gran medida a la condena de Sirius, por lo que hay razones para temer por su vida.', '2004');
INSERT INTO `gamovie`.`movies` (`category`, `date`, `director`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `synopsis`, `year`) VALUES ('Fantasía', '2022-04-26', 'Mike Newell', 'Warner Bros', 'harry4.jpg', '10', 'Harry Potter y el cáliz de fuego', '6.6', 'La cuarta parte de la serie del niño mago comienza con la Copa Internacional de Quidditch. Cuenta también el inicio de la atracción por Cho Chang y otro año de magia, en el que una gran sorpresa obligará a Harry a enfrentarse a muchos desafíos temibles. También habrá un torneo de magia para tres escuelas, y el temido regreso de "Aquel-que-no-debe-ser-nombrado".', '2005');




#GAMES

INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`,`synopsis`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'From Software','Elden Ring es un juego de fantasía, acción y mundo abierto con elementos de rol como estadísticas, armas y hechizos. Levántate, empañado, y déjate guiar por la gracia para blandir el poder del Elden Ring y convertirte en un Elden Lord en las Tierras Intermedias.', 'eldenRing.jpg', '10', 'Elden Ring', '9.4', '2022');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'Nintendo', 'botw.jpg', '10', 'The Legend of Zelda: Breath of the Wild', '9.2', '2017');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Mundo Abierto', '2022-05-05', 'Rockstar', 'gta.jpg', '10', 'Grand Theft Auto V', '9.0', '2013');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'From Software', 'sekiro.jpg', '10', 'Sekiro™: Shadows Die Twice', '9.1', '2019');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'Nintendo', 'windWaker.jpg', '10', 'The Legend of Zelda: Wind Waker', '9.0', '2002');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Indie', '2022-05-05', 'Team Cherry', 'hollow.jpg', '10', 'Hollow Knight', '9.2', '2017');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Indie', '2022-05-05', 'Evil Impire', 'deadCells.jpg', '10', 'Dead Cells', '8.4', '2018');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Indie', '2022-05-05', 'ConcernedApe', 'stardew.jpg', '10', 'Stardew Valley', '8.7', '2016');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Naughty Dog', 'uncharted1.jpg', '10', 'Uncharted: La Fortuna de Drake', '7.7', '2007');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Naughty Dog', 'uncharted2.jpg', '10', 'Uncharted: El Reino de los Ladrones', '9.0', '2009');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Naughty Dog', 'uncharted3.jpg', '10', 'Uncharted: La Traición de Drake', '8.5', '2011');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Naughty Dog', 'uncharted4.jpg', '10', 'Uncharted: El Desenlace del Ladrón', '9.2', '2016');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Naughty Dog', 'unchartedLegacy.jpg', '10', 'Uncharted: El Legado Perdido', '8.4', '2017');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Naughty Dog', 'lastOfUs.jpg', '10', 'The Last of Us', '9.3', '2013');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Naughty Dog', 'lastOfUs2.jpg', '10', 'The Last of Us Part II', '9.3', '2020');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Mundo Abierto', '2022-05-05', 'Santa Monica', 'gow.jpg', '10', 'God of War', '9.4', '2018');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Hack and Slash', '2022-05-05', 'Santa Monica', 'gow1.jpg', '10', 'God of War I', '8.4', '2005');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Hack and Slash', '2022-05-05', 'Santa Monica', 'gow2.jpg', '10', 'God of War II', '8.6', '2007');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Hack and Slash', '2022-05-05', 'Santa Monica', 'gow3.jpg', '10', 'God of War III', '8.6', '2010');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Santa Monica', 'prince1.jpg', '10', 'Prince of Persia: Las Arenas del Tiempo', '8.2', '2003');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Santa Monica', 'prince2.jpg', '10', 'Prince of Persia: El Alma del Guerrero', '8.3', '2004');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Santa Monica', 'prince3.jpg', '10', 'Prince of Persia: Los Dos Tronos', '8.0', '2005');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'Guerrila Games', 'horizon2.jpg', '10', 'Horizon Forbidden West', '8.1', '2022');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'Guerrila Games', 'horizon.jpg', '10', 'Horizon Zero Dawn', '9.1', '2017');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'Bethesda', 'skyrim.jpg', '10', 'The Elder Scrolls V: Skyrim', '9.6', '2011');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'CD Projekt RED', 'witcher.jpg', '10', 'The Witcher 3: Wild Hunt', '9.2', '2015');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'From Software', 'bloodborne.jpg', '10', 'Bloodborne', '9.1', '2015');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'From Software', 'ds3.jpg', '10', 'Dark Souls III', '8.6', '2016');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'From Software', 'ds2.jpg', '10', 'Dark Souls II', '7.9', '2014');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'From Software', 'ds1.jpg', '10', 'Dark Souls', '8.7', '2011');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Traveller´s Tales', 'legoSkyWalker.jpg', '10', 'LEGO Star Wars: The Skywalker Saga', '8.2', '2022');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Reockstar Games', 'rdr2.jpg', '10', 'Red Dead Redemption 2', '9.4', '2018');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Reockstar Games', 'rdr.jpg', '10', 'Red Dead Redemption', '8.9', '2010');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Reockstar Games', 'GTAsanAndreas.jpg', '10', 'Grand Theft Auto: San Andreas', '9.3', '2004');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Aventura', '2022-05-05', 'Insomnias Games', 'marvelSpiderman.jpg', '10', 'Marvel`s Spider-Man', '9.0', '2018');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Zombis', '2022-05-05', 'Capcom', 'resident2.jpg', '10', 'Resident Evil 2', '9.3', '2019');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Zombis', '2022-05-05', 'Techland', 'dyingL.jpg', '10', 'Dying Light', '8.1', '2015');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Zombis', '2022-05-05', 'Turtle Rock Studios', 'l4d2.jpg', '10', 'Left 4 Dead 2', '8.9', '2009');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('Zombis', '2022-05-05', 'SIE Bend Studio', 'daysGone.jpg', '10', 'Days Gone', '7.5', '2019');
INSERT INTO `gamovie`.`games` (`category`, `date`, `distributor`, `image_address`, `n_votes`, `name`, `note`, `year`) VALUES ('RPG', '2022-05-05', 'Nintendo', 'ocarinaOfTime.jpg', '10', 'The Legend of Zelda: Ocarina of Time', '9.2', '1998');

